      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, json, curl
          coverage: none

      - name: Install Composer dependencies
        run: composer install --no-progress --prefer-dist

      - name: PHPStan
        run: vendor/bin/phpstan analyse --memory-limit=512M

      - name: PHPMD
        run: vendor/bin/phpmd app text cleancode,codesize,controversial,design
